# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_auto_20160610_0344'),
        ('cities_customized', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=128)),
                ('latitude', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_two', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_customized.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_customized.Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctors', models.ManyToManyField(to='doctors.Doctor')),
            ],
        ),
    ]
