# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_customized', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_two', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_customized.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_customized.Country')),
                ('doctors', models.ManyToManyField(to='doctors.Doctor')),
            ],
        ),
    ]
